# Generated by Django 4.2.7 on 2024-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid_tool", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArduinoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
