# Generated by Django 4.2.7 on 2024-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid_tool", "0002_arduinodata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arduinodata",
            old_name="data",
            new_name="model",
        ),
        migrations.AddField(
            model_name="arduinodata",
            name="rfid_uid",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
